# WARNING - Generated by {fusen} from dev/flat_xsquare.Rmd: do not edit by hand

#' Return cubic of input value
#' 
#' cubes the input value
#' 
#' @param .value numerical input
#' @return cubed result of input
#' 
#' @export
#' @examples
#' xcubic(2)
xcubic <- function(.value){
    .value^3
}
