# WARNING - Generated by {fusen} from dev/flat_xsquare.Rmd: do not edit by hand

#' Return square of value
#'
#' @param .value numerical input
#' @return squeared result
#' @export
#'
#' @examples
#' xsquare(4)
#' xsquare(-2)
xsquare <- function(.value) {
  .value^2
}
